version: "3"

services:
  test-server-1:
    image: hashicorp/http-echo:latest
    command: -listen :3232
    networks:
      go-lanscan_default:

  test-server-2:
    image: hashicorp/http-echo:latest
    command: -listen :2323
    networks:
      go-lanscan_default:

  go-lanscan:
    # build:
    #   args:
    #     - BUILD_TAGS=debug
    #   context: .
    #   dockerfile: Dockerfile
    image: rgonnella/go-lanscan:latest
    command: --ports 2323,3232 --json
    depends_on:
      - test-server-1
      - test-server-2
    volumes:
      - ./reports:/reports
    networks:
      go-lanscan_default:

networks:
  go-lanscan_default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.1/28
         gateway: 172.18.0.1
